version: "3"
services:
  upload:
    image: filebrowser/filebrowser:s6
    container_name: upload
    ports:
      - "8888:80"
    networks:
      - hapi-fhir-network
    volumes:
      - ./csop/uploads:/srv

  web:
    build:
      context: user-portal/
      dockerfile: Dockerfile
    container_name: portal
    restart: always
    ports:
      - "80:80"
    networks:
      - hapi-fhir-network

  hapi-fhir-jpaserver-start:
    image: "hapiproject/hapi:latest"
    container_name: hapi-fhir-jpaserver-start
    volumes:
      - ./hapi-fhir-server:/data/hapi
    restart: on-failure
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - hapi-fhir-network

  hapi-fhir-mysql:
    image: mysql:latest
    container_name: hapi-fhir-mysql
    command: --lower_case_table_names=1
    restart: always
    env_file:
      - .hapimysqlenv
    volumes:
      - ./hapi-fhir-mysql:/var/lib/mysql

  db:
    image: postgres:11-alpine
    env_file:
      - .pgenv
    expose:
      - 5432
    networks:
      - hapi-fhir-network
    volumes:
      - kong-db:/var/lib/postgresql/data

  kong:
    image: kong:latest
    user: root
    env_file:
      - .kongenv
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    restart: on-failure:5
    depends_on:
      - db
    networks:
      - hapi-fhir-network

  konga-prepare:
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u postgresql://kong:kong@db:5432/konga"
    networks:
      - hapi-fhir-network
    restart: on-failure
    depends_on:
      - db

  kong-migration:
    image: ${KONG_DOCKER_TAG:-kong:latest}
    command: kong migrations bootstrap
    networks:
      - hapi-fhir-network
    restart: on-failure
    env_file:
      - .kongenv
    depends_on:
      - db

  konga:
    image: pantsel/konga:latest
    restart: always
    networks:
      - hapi-fhir-network
    environment:
      DB_ADAPTER: postgres
      DB_URI: postgresql://kong:kong@db:5432/konga
      NODE_ENV: production
    depends_on:
      - db
    ports:
      - "1337:1337"

volumes:
  hapi-fhir-mysql:
  hapi-fhir-server:
  kong-db:
networks:
  hapi-fhir-network:
