version: "3.9"
services:
  file-uploader:
    image: healthtag/file-uploader
    container_name: file-uploader
    ports:
      - "8888:3000"
    networks:
      - hapi-fhir-network
    restart: on-failure
    volumes:
      - ./workingdir:/app/workingdir
    env_file:
      - .file-uploader.env

  fhir-transformer:
    image: healthtag/fhir-transformer
    container_name: fhir-transformer
    networks:
      - hapi-fhir-network
    restart: on-failure
    volumes:
      - ./workingdir:/app/workingdir
    env_file:
      - .fhir-transformer.env

  web:
    build:
      context: user-portal/
      dockerfile: Dockerfile
    container_name: portal
    restart: always
    ports:
      - "80:80"
    networks:
      - hapi-fhir-network

  hapi-fhir-jpaserver-start:
    image: "healthtag/hapi-fhir-jpaserver:latest"
    container_name: hapi-fhir-jpaserver-start
    volumes:
      - ./hapi-data:/data/hapi
    restart: on-failure
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - hapi-fhir-network
    env_file:
      - .hapi.env

  hapi-fhir-postgres:
    image: postgres:15-alpine
    shm_size: 256MB
    container_name: hapi-fhir-postgres
    restart: always
    env_file:
      - .hapi-postgres.env
    volumes:
      - ./hapi-postgres-data:/var/lib/postgresql/data
    networks:
      - hapi-fhir-network
    command: " -c shared_buffers=2GB -c max_wal_size=3GB -c max_connections=100 -c max_prepared_transactions=100 -c max_locks_per_transaction=128 "

  kong-postgres:
    image: postgres:15-alpine
    env_file:
      - .kong-postgres.env
    networks:
      - hapi-fhir-network
    volumes:
      - ./kong-postgres-data:/var/lib/postgresql/data

  kong:
    image: kong/kong-gateway:3.1.0.0-ubuntu
    user: root
    env_file:
      - .kong.env
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8443:8443"
      - "8444:8444"
    restart: on-failure:5
    depends_on:
      - kong-postgres
    networks:
      - hapi-fhir-network

  kong-migration:
    image: kong/kong-gateway:3.1.0.0-ubuntu
    command: kong migrations bootstrap
    networks:
      - hapi-fhir-network
    restart: on-failure
    env_file:
      - .kong.env
    depends_on:
      - kong-postgres

networks:
  hapi-fhir-network:
